version: '2'

services:
  git:
    build: ./images/bitbucket
    container_name: git.DOMAINNAME
    hostname: git.DOMAINNAME
    # 8888 is our custom port we set up for a separate/additional connection.
    expose:
      - "8888"
      - "7990"
    ports:
      # 7999 is SSH for bitbucket
      - "7999:7999"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ATLASSIANTOPDIR/bitbucket:/var/atlassian/bitbucket

  projects:
    build:  ./images/jira
    container_name: projects.DOMAINNAME
    hostname: projects.DOMAINNAME
    environment:
      - CATALINA_OPTS="-Datlassian.plugins.enable.wait=300" "-Xmx768m" "-Xms512m" "-Dorg.apache.catalina.SESSION_COOKIE_NAME=jirasession" "-Duser.timezone="
    expose:
      - "8888"
      - "8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ATLASSIANTOPDIR/jira:/var/atlassian/jira

  codereview:
    build:  ./images/crucible
    container_name: codereview.DOMAINNAME
    hostname: codereview.DOMAINNAME
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ATLASSIANTOPDIR/crucible:/var/atlassian/crucible

  build:
    build: ./images/jenkins
    container_name: build.DOMAINNAME
    hostname: build.DOMAINNAME
    ports:
      - "50000:50000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - CODETOPDIR/jenkins:/var/jenkins_home

  artifacts:
    build:  ./images/artifactory
    container_name: artifacts.DOMAINNAME
    hostname: artifacts.DOMAINNAME
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - CODETOPDIR/artifactory/backup:/artifactory/backup
      - CODETOPDIR/artifactory/data:/artifactory/data
      - CODETOPDIR/artifactory/logs:/artifactory/logs

  haproxy:
    build: ./images/haproxy
    container_name: haproxy.DOMAINNAME
    hostname: haproxy.DOMAINNAME
    depends_on:
      - atlassiandb
      - build
      - artifacts
      - projects
      - codereview
      - git
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - CODETOPDIR/haproxy:/var/haproxy
  cadvisor:
    # Note: cadvisor is not part of haproxy setup. It exposes it's port on the dockerhost.
    #       This is intentional.
    image: google/cadvisor:latest 
    container_name: cadvisor.DOMAINNAME
    hostname: cadvisor.DOMAINNAME
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
