# FROM naesheim/artifactory:4.16.0
# Naesheim's image does not have necessary redirects as yet. 
# Also, the Dockerfile for Naesheim's image is not publicly available, so it is a blackbox. 
# It is also a good idea to mount the data, backup and logs separately as mattgruter does in his artifactory image.
# That way logs can be monitored individually, for example.
# Also backups can be handled separately without worrying about mounting the entire directory structure containing the main data.
# So until this image is improved, I (humbly) suggest using mattgruter's image. (That is also 200MB) 

FROM: mattgruter/artifactory:3.9


