version: '2'

services:
  bitbucket:
    image: staci/bitbucket:0.1
    container_name: bitbucket
    hostname: bitbucket
    expose:
      - "7990"
      - "7999"
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - /data/atlassian/bitbucket:/var/atlassian/bitbucket
  crucible:
    image: staci/crucible:0.1
    container_name: crucible
    hostname: crowd
    expose:
      - "8060"
    ports:
      - "8060:8060"
    volumes:
    - /data/atlassian/crucible:/var/atlassian/crucible
  atlassiandb:
    image: staci/atlassiandb:0.1
    container_name: atlassiandb
    hostname: atlassiandb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass_word
    volumes:
      - /data/atlassian/atlassiandb:/var/lib/mysql
