version: '2'

services:
  bitbucket:
    image: staci/bitbucket:0.1
    container_name: bitbucket
    hostname: bitbucket
    expose:
      - "7990"
      - "7999"
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - "constraint:node==hoeghh-bitbucket"
    networks:
      - back
  crucible:
    image: staci/crucible:0.1
    container_name: crucible
    hostname: crucible
    expose:
      - "8060"
    ports:
      - "8060:8060"
    environment:
      - "constraint:node==hoeghh-crucible"
    networks:
      - back
  atlassiandb:
    image: staci/atlassiandb:0.1
    container_name: atlassiandb
    hostname: atlassiandb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass_word
      - "constraint:node==hoeghh-mysql"
    networks:
      - back
networks:
  back:
    driver: overlay

